on:
  push:
    branches: [ master ]


name: Node.js

jobs:
  swap-slots:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
              
    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'rvoghaction'
        slot-name: 'staging' 

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az webapp deployment slot swap --slot staging --name 'rvoghaction' --resource-group 'rvo-gh-actions'
          
    # Azure logout 
    - name: logout
      run: |
        az logout
